error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:42:19
   |
LL |     debug_assert!(bool_mut(&mut 3));
   |                   ^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::debug-assert-with-mut-call` implied by `-D warnings`

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:43:20
   |
LL |     debug_assert!(!bool_mut(&mut 3));
   |                    ^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_eq!`
  --> $DIR/debug_assert_with_mut_call.rs:45:25
   |
LL |     debug_assert_eq!(0, u32_mut(&mut 3));
   |                         ^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_eq!`
  --> $DIR/debug_assert_with_mut_call.rs:46:22
   |
LL |     debug_assert_eq!(u32_mut(&mut 3), 0);
   |                      ^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_ne!`
  --> $DIR/debug_assert_with_mut_call.rs:48:25
   |
LL |     debug_assert_ne!(1, u32_mut(&mut 3));
   |                         ^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_ne!`
  --> $DIR/debug_assert_with_mut_call.rs:49:22
   |
LL |     debug_assert_ne!(u32_mut(&mut 3), 1);
   |                      ^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:64:19
   |
LL |     debug_assert!(S.bool_self_mut());
   |                   ^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:65:20
   |
LL |     debug_assert!(!S.bool_self_mut());
   |                    ^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:66:19
   |
LL |     debug_assert!(S.bool_self_ref_arg_mut(&mut 3));
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:67:19
   |
LL |     debug_assert!(S.bool_self_mut_arg_ref(&3));
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:68:19
   |
LL |     debug_assert!(S.bool_self_mut_arg_mut(&mut 3));
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_eq!`
  --> $DIR/debug_assert_with_mut_call.rs:70:22
   |
LL |     debug_assert_eq!(S.u32_self_mut(), 0);
   |                      ^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_eq!`
  --> $DIR/debug_assert_with_mut_call.rs:71:22
   |
LL |     debug_assert_eq!(S.u32_self_mut_arg_ref(&3), 0);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_eq!`
  --> $DIR/debug_assert_with_mut_call.rs:72:22
   |
LL |     debug_assert_eq!(S.u32_self_ref_arg_mut(&mut 3), 0);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_eq!`
  --> $DIR/debug_assert_with_mut_call.rs:73:22
   |
LL |     debug_assert_eq!(S.u32_self_mut_arg_mut(&mut 3), 0);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_ne!`
  --> $DIR/debug_assert_with_mut_call.rs:75:22
   |
LL |     debug_assert_ne!(S.u32_self_mut(), 1);
   |                      ^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_ne!`
  --> $DIR/debug_assert_with_mut_call.rs:76:22
   |
LL |     debug_assert_ne!(S.u32_self_mut_arg_ref(&3), 1);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_ne!`
  --> $DIR/debug_assert_with_mut_call.rs:77:22
   |
LL |     debug_assert_ne!(S.u32_self_ref_arg_mut(&mut 3), 1);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_ne!`
  --> $DIR/debug_assert_with_mut_call.rs:78:22
   |
LL |     debug_assert_ne!(S.u32_self_mut_arg_mut(&mut 3), 1);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_eq!`
  --> $DIR/debug_assert_with_mut_call.rs:86:22
   |
LL |     debug_assert_eq!(v.pop(), Some(1));
   |                      ^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_ne!`
  --> $DIR/debug_assert_with_mut_call.rs:87:31
   |
LL |     debug_assert_ne!(Some(3), v.pop());
   |                               ^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:90:19
   |
LL |     debug_assert!(bool_mut(a));
   |                   ^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:93:31
   |
LL |     debug_assert!(!(bool_ref(&u32_mut(&mut 3))));
   |                               ^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert_eq!`
  --> $DIR/debug_assert_with_mut_call.rs:96:22
   |
LL |     debug_assert_eq!(v.pop().unwrap(), 3);
   |                      ^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:100:19
   |
LL |     debug_assert!(bool_mut(&mut 3), "w/o format");
   |                   ^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:102:19
   |
LL |     debug_assert!(bool_mut(&mut 3), "{} format", "w/");
   |                   ^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:107:9
   |
LL |         bool_mut(&mut x);
   |         ^^^^^^^^^^^^^^^^

error: do not call a function with mutable arguments inside of `debug_assert!`
  --> $DIR/debug_assert_with_mut_call.rs:114:9
   |
LL |         bool_mut(&mut x);
   |         ^^^^^^^^^^^^^^^^

error: aborting due to 28 previous errors

