error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:28:26
   |
LL |     with_none_and_format.expect(&format!("Error {}: fake error", error_code));
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("Error {}: fake error", error_code))`
   |
   = note: `-D clippy::expect-fun-call` implied by `-D warnings`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:31:26
   |
LL |     with_none_and_as_str.expect(format!("Error {}: fake error", error_code).as_str());
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("Error {}: fake error", error_code))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:41:25
   |
LL |     with_err_and_format.expect(&format!("Error {}: fake error", error_code));
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| panic!("Error {}: fake error", error_code))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:44:25
   |
LL |     with_err_and_as_str.expect(format!("Error {}: fake error", error_code).as_str());
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| panic!("Error {}: fake error", error_code))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:56:17
   |
LL |     Some("foo").expect(format!("{} {}", 1, 2).as_ref());
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("{} {}", 1, 2))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:77:21
   |
LL |         Some("foo").expect(&get_string());
   |                     ^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| { panic!(get_string()) })`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:78:21
   |
LL |         Some("foo").expect(get_string().as_ref());
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| { panic!(get_string()) })`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:79:21
   |
LL |         Some("foo").expect(get_string().as_str());
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| { panic!(get_string()) })`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:81:21
   |
LL |         Some("foo").expect(get_static_str());
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| { panic!(get_static_str()) })`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:82:21
   |
LL |         Some("foo").expect(get_non_static_str(&0));
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| { panic!(get_non_static_str(&0).to_string()) })`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:86:16
   |
LL |     Some(true).expect(&format!("key {}, {}", 1, 2));
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("key {}, {}", 1, 2))`

error: use of `expect` followed by a function call
  --> $DIR/expect_fun_call.rs:92:17
   |
LL |         opt_ref.expect(&format!("{:?}", opt_ref));
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|| panic!("{:?}", opt_ref))`

error: aborting due to 12 previous errors

